# Generated by Django 5.2.4 on 2025-08-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatlog_predicted_intent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatlog',
            old_name='timestamp',
            new_name='message_time',
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='predicted_intent',
            field=models.CharField(max_length=10000),
        ),
    ]
